FROM node:19.6.1-alpine

WORKDIR ./Zamburinhas/

COPY package*.json ./
COPY server.js ./
COPY import.sh ./
COPY ./BackEnd ./BackEnd
COPY ./BD ./BD 

EXPOSE 4000
RUN npm install express

CMD ["sh","import.sh"]
CMD ["npm","start"]
